---
title: "CO2 displacement manuscript figures"
author: "Anthony Darrouzet-Nardi, Briana Salcido"
date: "2025-08-13"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)
```


```{r packages}
library(tidyverse)
library(readxl)
library(lubridate) ; Sys.setenv(TZ = "UTC")
library(ggpubr)
library(scales)
library(kableExtra)

theme_set(theme_bw() %+replace%
  theme(axis.line = element_line(colour = "black"),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  legend.background = element_blank(),
  legend.key = element_blank(),
  strip.background = element_blank(),
  plot.background = element_blank() ))

theme_no_x <- theme(axis.text.x = element_blank(), 
  panel.border = element_blank(), axis.title.x = element_blank())
```


```{r data_import}
#jornada
bajada <- read_csv("sat_site_clean.csv.gz") %>% 
  transmute(DateTime, 
            AirP = `AirP (kPa)`, 
            SoilT = `Soil T 15cm (Apogee, deg C)`,
            CO2_15cm = `CO2 15cm_L (%)`, 
            VWC_15cm = `VWC 15cm cm(m3/m3)`, 
            eosfdFlux = under_eos_co2_flux) %>%
  filter(DateTime < as.POSIXct("2022-06-01")) %>% 
  left_join(read_xlsx("southpit10cm.xlsx"))

tower_precipitation <- read_xlsx("JTower_Precip.xlsx")

#orchard
combined_fine <- read_csv("pecan_fine_clean.csv.gz") %>% 
  transmute(DateTime, 
            AirP = `pecan_Air_P (kPa)`, 
            Soil_T_30cm = `pecan_SoilT_30cm (C)`,
            CO2_30cm = `pecan_CO2_30cm (%)`, 
            VWC_30cm = pecan_VWC_30, 
            Flux = eosfd_Flux) %>% 
  filter(DateTime < as.POSIXct("2023-01-01"))

rain5r <- read_csv("AboveCanopy_5R_Rainfall.csv") %>% 
  mutate(DateTime = mdy_hm(TIMESTAMP))
```


```{r ficks_law}
#Ficks Law of Diffusion equation
#F = - (0.66 * porosity * vol. gas content * free air D) * dC/dx

R = 8.314 #gas constant
co2diffusivity = 1.381e-5

#jornada
bulk_density = mean(c(1.44, 1.38, 1.64)) # Dacey 2024 thesis 0-15 cm
porosity = 1 - (bulk_density / 2.71) # porosity = 1 - (bulk density/particle density)
gastortuosity = 0.66 * (porosity - bajada$VWC_15cm)
Ds = gastortuosity * co2diffusivity
jornada_surface_CO2 <- 474 # based on long-term match with chamber flux (see S2)
Dc = jornada_surface_CO2 - (bajada$CO2_15cm * 1e4) #subtract concentrations (convert them to ppm from %)
distance = 0.15 # meters

#impute first day of soil temps for diffusion calc (duplicate next day)
#then calculate Fick's law diffusive flux
bajada <- bajada %>% mutate(
  SoilT = if_else(between(DateTime, ymd_hms("2021-08-27 13:05:00"),
    ymd_hms("2021-08-28 00:00:00")), lead(SoilT, n = 288), SoilT), 
  CO2_diffusion = -Ds * Dc * ((AirP * 1e3) / ((SoilT + 273.15)) / (R * distance)))

#orchard
bulk_density_fine = mean(c(1.28, 1.41, 1.33, 1.29, 1.2816, 1.37988)) # Dacey 2024 thesis 0-30 cm
porosity_fine = 1 - (bulk_density_fine / 2.65)
gastortuosity_fine = 0.66 * (porosity_fine - combined_fine$VWC_30cm)
Ds_fine = gastortuosity_fine * co2diffusivity
ivey_surface_CO2 <- 573 # measured empirically - 19 exetainer samples
Dc_fine = ivey_surface_CO2 - (combined_fine$CO2_30cm * 1e4)
distance_orchard = 0.30

combined_fine <- combined_fine %>% 
  mutate(orchard_diffusion = -Ds_fine * Dc_fine * ((AirP * 1000) / 
    ((Soil_T_30cm + 273.15)) / (R * distance_orchard)))

```


```{r Figure_3, fig.height=9, fig.width=9}
f3 <- bajada %>% filter(DateTime > as.POSIXct("2022-03-20 00:00:00"), 
  DateTime < as.POSIXct("2022-03-23 00:00:00"))

water_add <- function() list(
  geom_rect(inherit.aes = FALSE, 
  aes(xmin = ymd_hms("2022-03-21 08:20:00"), 
  xmax = ymd_hms("2022-03-21 10:00:00"), ymin = -Inf, ymax = Inf), 
  fill = "lightcyan1"))

ggarrange(

f3 %>% ggplot(aes(DateTime, eosfdFlux)) +
  water_add() +
  geom_line(color = "seagreen") +
  scale_x_datetime(date_breaks = "day") +
  annotate("text", x = as.POSIXct("2022-03-21 05:00:00"),
    y = 0.8, label = "Event 1", size = 4)  +
  labs(title = "a.", y = expression(atop("Surface Flux (" * italic(F)[CO[2]] * ")",
    mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  theme_no_x
,
f3 %>% ggplot(aes(DateTime, CO2_diffusion))+
  water_add() +
  geom_line(color = "red4") +
  scale_x_datetime(date_breaks = "day") +
  labs(title = "b.", y = expression(atop("Diffusion (" * italic(F)[CO[2]]^diff * ")",
    mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  theme_no_x
,
f3 %>% ggplot(aes(DateTime, SP_VWC_10cm_25T_LMA*100)) +
  water_add() +
  geom_line(color="mediumblue") +
  scale_x_datetime(date_breaks = "day", date_labels = "%b %e\n%H:%M") +
  labs(title = "c.", y = expression(atop("VWC (10cm)", "%")), x = "") +
  theme_no_x 
,
tower_precipitation %>% filter(DateTime > range(f3$DateTime)[1], 
  DateTime < range(f3$DateTime)[2]) %>%
ggplot(aes(x = DateTime, y = Precipitation)) +
  water_add() +
  geom_bar(stat = "identity", fill = "steelblue2") +
  scale_x_datetime(date_breaks = "day") +
  ylim(0, 20) +
  labs(title = "d.", y = "Precipitation \n mm", x = "")  +
  scale_x_datetime(date_breaks = "1 day", date_labels = "%b %e\n%H:%M",
                   limits = range(f3$DateTime)) +
  theme(panel.border = element_blank()) 
,
ncol = 1, align ="hv")

```


```{r figure_4, fig.height=9, fig.width=9}
f4 <- bajada %>% filter(DateTime > as.POSIXct("2021-08-27 00:00:00"),
  DateTime < as.POSIXct("2021-08-29 00:00:00"))

water_add <- function() list(
  geom_rect(inherit.aes = FALSE,
    aes(xmin = ymd_hms("2021-08-27 14:45:00"),
        xmax = ymd_hms("2021-08-27 18:35:00"), ymin = -Inf, ymax = Inf),
    fill = "lightcyan1"))

ggarrange(

f4 %>% ggplot(aes(DateTime, eosfdFlux)) +
  water_add() +
  geom_line(color="seagreen") +
  annotate("text", x = as.POSIXct("2021-08-27 12:45:00"),
    y = 3, label = "Event 2", size = 4)  +
  labs(title = "a.", y = expression(atop("Surface Flux (" * italic(F)[CO[2]] * ")",
    mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  scale_x_datetime(date_breaks = "day")  +
  theme_no_x
,
f4 %>% ggplot(aes(DateTime, CO2_diffusion))+
  water_add() +
  geom_line( aes(y=CO2_diffusion), color="red4")+
  labs(title = "b.", y = expression(atop("Diffusion (" * italic(F)[CO[2]]^diff * ")",
    mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  scale_x_datetime(date_breaks = "day")  +
  theme_no_x
,
f4 %>% ggplot(aes(DateTime, SP_VWC_10cm_25T_LMA*100)) +
  water_add() +
  geom_line(color="mediumblue") +
  scale_x_datetime(date_breaks = "day", date_labels = "%b %e\n%H:%M")+
  labs(title = "c.", y = expression(atop("VWC (10 cm)", "%")), x = "") +
  theme_no_x
,
tower_precipitation %>% filter(DateTime > range(f4$DateTime)[1], 
    DateTime < range(f4$DateTime)[2]) %>%
  group_by(hour = lubridate::floor_date(DateTime, '30 min')) %>%
  summarize(sumPrecipitation = sum(Precipitation)) %>%
ggplot(aes(hour, sumPrecipitation)) +
  water_add() +
  geom_bar(stat = "identity", fill = "steelblue2") +
  scale_x_datetime(date_breaks = "1 day", date_labels = "%b %e\n%H:%M",
    limits = range(f4$DateTime)) +
  labs(title = "d.", y = "Precipitation, \n mm", x = "")  +
  theme(panel.border = element_blank())
,
ncol = 1, align ="hv")

```


```{r figure_5, fig.height=4.5, fig.width=9}
f5 <- bajada %>% filter(DateTime > ymd_hms("2021-03-19 06:00:00"),
  DateTime < ymd_hms("2021-03-20 00:00:00"))

water_add <- function() list(
  geom_rect(inherit.aes = FALSE,
    aes(xmin = ymd_hms("2021-03-19 15:55:00"),
        xmax = ymd_hms("2021-03-19 22:00:00"), ymin = -Inf, ymax = Inf),
    fill = "lightcyan1"),
  geom_rect(inherit.aes = FALSE,
    aes(xmin = ymd_hms("2021-03-19 15:56:00"),
        xmax = ymd_hms("2021-03-19 17:11:00"), ymin = 0, ymax = 0.01),
    fill = "mediumblue", alpha = 0.2),
  geom_rect(inherit.aes = FALSE,
    aes(xmin = ymd_hms("2021-03-19 20:12:00"),
        xmax = ymd_hms("2021-03-19 21:30:00"), ymin = 0, ymax = 0.01),
    fill = "mediumblue", alpha = 0.2))

ggarrange(

f5 %>% ggplot(aes(DateTime, eosfdFlux)) +
  water_add() +
  geom_line(color = "seagreen") +
  scale_x_datetime(date_breaks = "3 hour", labels = date_format("%D\n%H:%M")) +
  annotate("text", x = as.POSIXct("2021-03-19 15:10:00"),
    y = 2.35, label = "Event 3", size = 4)  +
  labs(title = "a.", y = expression(atop("Surface Flux (" * italic(F)[CO[2]] * ")",
    mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  theme_no_x
,
f5 %>% ggplot(aes(DateTime, SP_VWC_10cm_25T_LMA*100)) +
  water_add() +
  geom_line(color="mediumblue") +
  scale_x_datetime(date_breaks = "3 hour", date_labels = "%b %e\n%H:%M") +
  labs(title = "b.", y = expression(atop("VWC (10cm)", "%")), x = "") +
  theme(panel.border = element_blank())
,
ncol = 1, align ="hv" )
```


```{r figure_6, fig.height=9, fig.width=9}

f6 <- combined_fine %>% filter(DateTime > as.POSIXct("2022-08-16 12:00:00"), 
  DateTime < as.POSIXct("2022-08-22 12:00:00"))

water_add <- function() list(
  geom_rect(inherit.aes = FALSE,
    aes(xmin = ymd_hms("2022-08-17 13:10:00"),
        xmax = ymd_hms("2022-08-17 13:30:00"), ymin = -Inf, ymax = Inf),
    fill = "lightcyan"),
    geom_rect(inherit.aes = FALSE,
    aes(xmin = ymd_hms("2022-08-16 22:30:00"),
        xmax = ymd_hms("2022-08-17 01:45:00"), ymin = -Inf, ymax = Inf),
    fill = "lightcyan"))


ggarrange(

f6 %>% filter(DateTime < ymd("2022-08-19")) %>% #truncate later values due to platform failure
  ggplot(aes(DateTime, Flux)) +
    geom_rect(inherit.aes = FALSE,
    aes(xmin = ymd_hms("2022-08-16 22:30:00"),
        xmax = ymd_hms("2022-08-17 01:45:00"), ymin = -Inf, ymax = Inf),
    fill = "lightcyan") +
  geom_line(color="seagreen") +
  scale_x_datetime(limits = range(f6$DateTime)) +
  annotate("text", x = as.POSIXct("2022-08-16 17:00:00"),
    y = 18, label = "Event 4", size = 4)  +
  annotate("text", x = as.POSIXct("2022-08-17 19:00:00"),
    y = 18, label = "Event 5", size = 4)  +
  labs(title = "a.", y = expression(atop("Surface Flux (" * italic(F)[CO[2]] * ")",
    mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  theme_no_x
,
f6 %>% ggplot(aes(DateTime, orchard_diffusion)) +
  water_add() + 
  geom_line(color="red4") +
  labs(title = "b.", y = expression(atop("Diffusion (" * italic(F)[CO[2]]^diff * ")",
                                        mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  theme_no_x
,
f6 %>% ggplot(aes(DateTime, VWC_30cm*100))+
  water_add() + 
  geom_line(color="mediumblue") +
  labs(title = "c.", y = expression(atop("VWC 30 cm", "%")), x = "")  +
  theme_no_x
,
rain5r %>%
    filter(between(DateTime, min(f6$DateTime), max(f6$DateTime))) %>%
    group_by(day = lubridate::floor_date(DateTime, 'hour')) %>%
    summarize(Precipitation = sum(P)) %>%
  ggplot(aes(x = day, y = Precipitation)) +
  water_add() + 
  geom_bar(stat = "identity", fill = "steelblue2") +
  scale_x_datetime(date_breaks = "1 day", date_labels = "%b %e\n%H:%M",
                   limits = range(f6$DateTime)) +
  labs(title="d.", y = "Precipitation \n mm", x = "") +
  theme(panel.border = element_blank())
,
ncol = 1, align ="hv")

```

```{r figure_6_inset, fig.width=4, fig.height=2}
#inset
combined_fine %>%
  filter(DateTime > as.POSIXct("2022-08-17 10:55:00"), 
    DateTime < as.POSIXct("2022-08-17 15:05:00")) %>%
ggplot(aes(DateTime, Flux)) +
  geom_rect(inherit.aes = FALSE,
    aes(xmin = ymd_hms("2022-08-17 13:10:00"),
        xmax = ymd_hms("2022-08-17 13:30:00"), ymin = -Inf, ymax = Inf),
    fill = "lightcyan") +
  geom_line(color="seagreen") +
  geom_point(color="seagreen") +
  scale_x_datetime(date_breaks = "1 hour", labels = date_format("%b %e\n%H:%M")) +
  labs(y = expression(atop("Surface Flux (" * italic(F)[CO[2]] * ")",
    mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  theme(panel.border = element_blank())
```


```{r figure_7}
bajada %>%
  select(DateTime, eosfdFlux, CO2_diffusion) %>% 
  filter(DateTime > ymd("2021-09-01"), DateTime < ymd("2022-05-01")) %>%
  mutate(mWC_1_2_1 = approx(x = tower_precipitation$DateTime,
    y = tower_precipitation$mWC_1_2_1, xout = DateTime, # nearest 30-min value
    method = "constant", f = 0.5)$y) %>%                # midpoint → closest
  drop_na(mWC_1_2_1) %>%
ggplot(aes(eosfdFlux, CO2_diffusion, col = mWC_1_2_1)) +
  geom_point(alpha = 0.5, position = position_jitter(), size = 0.2) + 
  geom_abline(intercept = -3:1, slope = 1, col = "gray80", linetype = "dashed") +
  geom_abline(intercept = 0, slope = 1) +
  geom_hline(yintercept = 0, col = "gray60") +
  geom_vline(xintercept = 0, col = "gray60") +
  scale_color_gradient(low = "tan", high = "blue") +
  labs(title = "a.", x = expression("Surface Flux (" * italic(F)[CO[2]] * "), " *
      mu * "mol m"^"-2" * "s"^"-1"),
    y = expression("Diffusion (" * italic(F)[CO[2]]^diff * "), " *
      mu * "mol m"^"-2" * "s"^"-1"), col = "VWC 10 cm (%)") +
  scale_y_continuous(breaks = c(0, 1)) +
  coord_equal()

combined_fine %>% filter(as_date(DateTime) > as_date("2022-08-01"),
    as_date(DateTime) < as_date("2022-08-19")) %>% 
ggplot(aes(Flux, orchard_diffusion, col = VWC_30cm*100)) +
  geom_point(position = position_jitter(), size = 0.3) + 
#  geom_abline(intercept = -20:5, slope = 1, col = "gray80", linetype = "dashed") +
  geom_abline(intercept = 0, slope = 1) +
  geom_hline(yintercept = 0, col = "gray60") +
  geom_vline(xintercept = 0, col = "gray60") +
  scale_color_gradient(low = "tan", high = "blue") +
  labs(title = "b.", x = expression("Surface Flux (" * italic(F)[CO[2]] * "), " *
      mu * "mol m"^"-2" * "s"^"-1"),
    y = expression("Diffusion (" * italic(F)[CO[2]]^diff * "), " *
      mu * "mol m"^"-2" * "s"^"-1"), col = "VWC 30 cm (%)") +
  scale_y_continuous(breaks = c(0,1,2), limits = c(-0.25,2)) +
  coord_equal()
```


```{r pulse_size_function}
displacement <- function(data, porosity, background_range, pulse_range, 
  VWC = "SP_VWC_10cm_25T_LMA", CO2 = "CO2_15cm", soilT = "SoilT", AirP = "AirP",
  chamber = "eosfdFlux") {

  background <- data %>%
    filter(between(DateTime, background_range[1], background_range[2]))
  pulse <- data %>%
    filter(between(DateTime, pulse_range[1], pulse_range[2]))
  
  background_flux <- mean(background[[chamber]], na.rm = TRUE)
  vol_CO2 <- (porosity - background[[VWC]]) * (background[[CO2]] / 100)
  Temp_K <- background[[soilT]] + 273.15
  P_atm <- background[[AirP]] / 101.325

  pore_space_co2_ppm <- mean(background[[CO2]], na.rm = TRUE) * 1e4
  pore_space_co2 <- mean((P_atm * vol_CO2) / (8.205733847e-5 * Temp_K), na.rm = TRUE) * 1e3
  chamber_pulse_size <- sum(pulse[[chamber]] - background_flux, na.rm = TRUE) * 300 / 1e3

  list(
    `Air-filled pore space proportion` = mean(porosity - background[[VWC]]) %>% round(., 2),
    `Pore space CO2 (ppm)` = pore_space_co2_ppm %>% round(., 0),
    `Background flux (umol m-2 s-1)` = background_flux %>% round(., 2),
    `Pulse length` = pulse_range[2] - pulse_range[1],
    `Chamber pulse size (mmol m-2)` = chamber_pulse_size %>% round(., 1),
    `Depth (cm) at which chamber pulse = pore space CO2` = 
       ((chamber_pulse_size * 100) / pore_space_co2) %>% round(., 0))
}
```

``` {r pulse_size_calcs}
list(

#Figure 3 small rain event - Jornada - ascending limb
displacement(bajada, porosity,
  background = ymd_hms(c("2022-03-21 07:15:00", "2022-03-21 08:15:00")),
  pulse_range = ymd_hms(c("2022-03-21 08:20:00", "2022-03-21 08:50:00")))
,
#Figure 4 large rain event - Jornada - ascending limb
displacement(bajada, porosity,
  background = ymd_hms(c("2021-08-27 13:40:00", "2021-08-27 14:40:00")),
  pulse_range = ymd_hms(c("2021-08-27 14:45:00", "2021-08-27 15:00:00")))
,
#Figure 5 artificial rain event - Jornada - ascending limb
bajada %>% 
  mutate(AirP = mean(AirP, na.rm = T), CO2 = 0.0550) %>% 
displacement(porosity,
  background = ymd_hms(c("2021-03-19 14:45:00", "2021-03-19 15:45:00")),
  pulse_range = ymd_hms(c("2021-03-19 15:55:00", "2021-03-19 16:10:00")),
  CO2 = "CO2", soilT = "T_8_10cm_Avg", AirP = "AirP")
,
#Figure 6 rain event - Pecan Orchard - ascending limb
displacement(combined_fine, porosity_fine,
  background = ymd_hms(c("2022-08-16 21:25:00", "2022-08-16 22:25:00")),
  pulse_range = ymd_hms(c("2022-08-16 22:30:00", "2022-08-17 00:50:00")),
  VWC = "VWC_30cm", CO2 = "CO2_30cm", soilT = "Soil_T_30cm", AirP = "AirP",
  chamber = "Flux") 
,
#Figure 6 irrigation event - Pecan Orchard - ascending limb
displacement(combined_fine, porosity_fine,
  background = ymd_hms(c("2022-08-17 12:05:00", "2022-08-17 13:05:00")),
  pulse_range = ymd_hms(c("2022-08-17 13:10:00", "2022-08-17 13:15:00")),
  VWC = "VWC_30cm", CO2 = "CO2_30cm", soilT = "Soil_T_30cm", AirP = "AirP",
  chamber = "Flux") 
,
#Figure 3 small rain event - Jornada
displacement(bajada, porosity,
  background = ymd_hms(c("2022-03-21 07:15:00", "2022-03-21 08:15:00")),
  pulse_range = ymd_hms(c("2022-03-21 08:20:00", "2022-03-21 10:00:00")))
,
#Figure 4 large rain event - Jornada
displacement(bajada, porosity,
  background = ymd_hms(c("2021-08-27 13:40:00", "2021-08-27 14:40:00")),
  pulse_range = ymd_hms(c("2021-08-27 14:45:00", "2021-08-27 18:35:00")))
,
#Figure 5 artificial rain event - Jornada
bajada %>% 
  mutate(AirP = mean(AirP, na.rm = T), CO2 = 0.0550) %>% 
displacement(porosity,
  background = ymd_hms(c("2021-03-19 14:45:00", "2021-03-19 15:45:00")),
  pulse_range = ymd_hms(c("2021-03-19 15:55:00", "2021-03-19 22:00:00")),
  CO2 = "CO2", soilT = "T_8_10cm_Avg", AirP = "AirP")
,
#Figure 6 rain event - Pecan Orchard
displacement(combined_fine, porosity_fine,
  background = ymd_hms(c("2022-08-16 21:25:00", "2022-08-16 22:25:00")),
  pulse_range = ymd_hms(c("2022-08-16 22:30:00", "2022-08-17 01:45:00")),
  VWC = "VWC_30cm", CO2 = "CO2_30cm", soilT = "Soil_T_30cm", AirP = "AirP",
  chamber = "Flux") 
,
#Figure 6 irrigation event - Pecan Orchard
displacement(combined_fine, porosity_fine,
  background = ymd_hms(c("2022-08-17 12:05:00", "2022-08-17 13:05:00")),
  pulse_range = ymd_hms(c("2022-08-17 13:10:00", "2022-08-17 13:25:00")),
  VWC = "VWC_30cm", CO2 = "CO2_30cm", soilT = "Soil_T_30cm", AirP = "AirP",
  chamber = "Flux")) %>% 

bind_rows(.id = "Event") %>% 
mutate(`Pulse length` = hms::as_hms(`Pulse length`), Event = rep(1:5, 2)) %>% 
#  across(where(is.numeric), ~ round(.x, 2))) %>% 
add_column(Pulse = rep(c("ascending", "total"), ea = 5), .after = "Event") %>%
add_column(`Event size (mm)` = rep(c(8,31,60,39,150), 2), .after = "Pulse") %>%
mutate(`Max displacement depth (cm)` = round(
  `Event size (mm)` * 0.1 / `Air-filled pore space proportion`, 0)) %>% 
kable %>% kable_styling(full_width = FALSE, bootstrap_options = 
  c("striped", "hover", "condensed", "responsive"))

```


```{r S2_effect_of_0cm_CO2}
j <- numeric(600)
for(x in 400:600) {
jsc <- x
Dc = jsc - (bajada$CO2_15cm * 1e4)
c2 <- bajada %>% mutate(CO2_diffusion =  -Ds * Dc * 
  ((AirP * 1000) / ((SoilT + 273.15))/ (R * distance)))
j[x] <- c2 %>%
  filter(DateTime > ymd("2021-09-01"), DateTime < ymd("2022-05-01")) %>% 
  pull(CO2_diffusion) %>% sum(., na.rm = TRUE) * 5 * 60 * 1e-6 * 12.011
}
rm(c2)

chamber_sum <- bajada %>%
    filter(DateTime > ymd("2021-09-01"), DateTime < ymd("2022-05-01")) %>% 
    pull(eosfdFlux) %>% sum(., na.rm = TRUE)  * 5 * 60 * 1e-6 * 12.011
co20cm_eq <- which.min(abs(j - chamber_sum))

tibble(surfaceco2 = 400:600, diffusive_flux = j[400:600]) %>% 
  ggplot(aes(surfaceco2, diffusive_flux)) +
    geom_line() +
  geom_hline(yintercept = chamber_sum, col = "red") +
  geom_segment(aes(x = co20cm_eq, xend = co20cm_eq, y = -Inf, yend = chamber_sum),
    col = "black", linetype = "dotted") +
  labs(x = expression("Soil surface "*CO[2]*" concentration, ppm"),
       y = expression(atop("Diffusion (" * italic(F)[CO[2]]^diff * ")", 
         mu * "mol m"^"-2" * "s"^"-1")))
```


```{r S3_jornada_over_time, fig.height = 5, fig.width=10, warning=FALSE}
ggarrange(
  
bajada %>%
ggplot(aes(DateTime, eosfdFlux)) +
  geom_hline(yintercept = 0, col = "lightgray") +
  geom_line(aes(y = eosfdFlux), color = "darkolivegreen") +
  labs(title = "a.", y = expression(atop("Surface Flux (" * italic(F)[CO[2]] * ")",
  mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  scale_x_datetime(date_breaks = "month", date_labels = "%b\n%Y",
    limits = c(as.POSIXct("2021-03-10"), as.POSIXct("2022-05-01"))) +
  geom_vline(xintercept = as.numeric(as.POSIXct(c("2021-03-19",
    "2021-08-27", "2022-03-21"))), linetype = "dashed",  
    color = "red", alpha = 0.5) +
  annotate("text", x = as.POSIXct(c("2021-04-03", "2021-09-11", "2022-04-05")),
    y = rep(5.4, 3), label = c("Event 3", "Event 2", "Event 1"), size = 4)  +
  theme_no_x
,
bajada %>%
  filter(DateTime > as.POSIXct("2021-03-10"), DateTime < as.POSIXct("2022-05-01")) %>%
ggplot(aes(DateTime, CO2_diffusion)) +
  geom_hline(yintercept = 0, col = "lightgray") +
  geom_line(color = "red4") +
  scale_x_datetime(date_breaks = "month", date_labels = "%b\n%Y",
    limits = c(as.POSIXct("2021-03-10"), as.POSIXct("2022-05-01"))) +
  labs(title = "b.", y = expression(atop("Diffusion (" * italic(F)[CO[2]]^diff * ")",
  mu * "mol m"^"-2" * "s"^"-1")), x = "") +
  theme(panel.border = element_blank(), axis.title.x = element_blank())
,
ncol = 1, align ="hv")
```

